## Ejercicios NumPy

In [2]:
# Importar el paquete numpy con el nombre np
import numpy as np

# Imprimir la versión numpy y la configuración
print(np.__version__)

1.22.4


### Creacion de arreglo

#### Cree una matriz numpy de tamaño 10, llena de ceros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Cree una matriz numpy con valores que van desde 10 a 49

In [3]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Cree una matriz numpy de 2*2 enteros, llena de unos

In [26]:
np.ones([2,2], dtype = int)

array([[1, 1],
       [1, 1]])

#### Cree una matriz numpy de 3*2 números flotantes, llena de unos

In [22]:
np.ones([3,2], dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Dada la matriz numpy X, cree una nueva matriz numpy con la misma forma y tipo que X, llena de unos

In [29]:
x = np.arange(4, dtype = int)
x

array([0, 1, 2, 3])

In [30]:
np.ones_like(x)

array([1, 1, 1, 1])

#### Dada la matriz numpy X, cree una nueva matriz numpy con la misma forma y tipo que X, llena de ceros

In [34]:
x = np.array([[1,2,3], [4,5,6]], dtype = int)

In [35]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

#### Cree una matriz numpy de 4*4 enteros, llena de cincos

In [58]:
np.ones([4,4], dtype= int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### Dada la matriz numpy X, cree una nueva matriz numpy con la misma forma y tipo que X, llena de sietes.

In [79]:
X = np.array([[2,3], [6,2]], dtype = int)

In [80]:
np.full_like(X, 7)

array([[7, 7],
       [7, 7]])

#### Cree una matriz numpy de identidad de 3*3 con unos en la diagonal y ceros en otros lugares

In [85]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Cree una matriz numpy, llena con 3 valores enteros aleatorios entre 1 y 10

In [101]:
np.random.randint(10, size=3)

array([7, 2, 2])

#### Cree una matriz numérica de 3x3x3, rellena con valores flotantes aleatorios

In [106]:
np.random.randn(3,3,3)

array([[[-0.09205402,  0.44627667, -0.46278317],
        [-1.10580855,  0.98265556, -1.11088176],
        [ 0.31895711, -0.66940627, -0.78631847]],

       [[ 0.01274845, -1.04579173,  0.0388862 ],
        [-1.14473174, -0.33628304,  1.32604455],
        [ 0.75792911,  0.44139549, -0.04953483]],

       [[-0.53840694, -1.26526942,  0.82966905],
        [ 1.16745211,  0.56827026,  2.81189408],
        [ 1.70656475,  0.10690056,  0.65709382]]])

#### Dada la lista de python X, conviértala en una matriz numpy Y

In [119]:
x = [1,2,3,4,5,6]
print(x, type(x))

[1, 2, 3, 4, 5, 6] <class 'list'>


In [118]:
Y = np.array(x)
print(Y, type(Y))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


#### Dada la matriz numpy X, haga una copia y guárdela en Y

In [126]:
X = np.array([[1,2,3], [4,5,6]], dtype = int)
print(X, id(X))

[[1 2 3]
 [4 5 6]] 140107538680304


In [127]:
Y = X.copy()
print(Y, id(Y))

[[1 2 3]
 [4 5 6]] 140106602747152


#### Crear una matriz numpy con números del 1 al 10

In [128]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Cree una matriz numpy con los números impares entre 1 y 10

In [132]:
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

#### Cree una matriz numpy con números del 1 al 10, en orden descendente

In [138]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### Cree una matriz numérica de 3 * 3, llena de valores que van de 0 a 8

In [146]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Muestra el tamaño de la memoria de la matriz Z numpy dada

In [151]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## Indexación de matrices

#### Dada la matriz numpy X, muestra su primer elemento

In [13]:
X = np.array([1,2,3,4,5,6])
X

array([1, 2, 3, 4, 5, 6])

In [16]:
X[0]

1

#### Dada la matriz numpy X, muestra su último elemento

In [17]:
X = np.array([1,2,3,4,5,6])
X[-1]

6

#### Dada la matriz numpy X, muestra sus primeros tres elementos

In [18]:
X = np.array([1,2,3,4,5,6])
X[0:3] # ¡recorda! que los elementos comienzan desde el indice 0

array([1, 2, 3])

#### Dada la matriz numpy X, muestra todos los elementos intermedios

In [24]:
X = np.array(['A','B','C','D','E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [25]:
#### Dada la matriz numpy X, muestra los elementos en posición inversa

In [36]:
X = np.array([1,2,3,4,5,6])
#np.flipud(X) Para una matriz 2-D, esto voltea las entradas en cada columna en la dirección hacia arriba/abajo
X[::-1]

array([6, 5, 4, 3, 2, 1])

#### Dada la matriz numpy X, muestra los elementos en una posición impar

In [44]:
X = np.array([1,2,3,4,5,6,7,8,9,10])
X[::2]

array([1, 3, 5, 7, 9])

#### Dada la matriz numpy X, muestra los elementos de la primera fila

In [57]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X[0]

array([1, 2, 3])

#### Dada la matriz numpy X, muestra los elementos de la última fila

In [61]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X[2]

array([7, 8, 9])

#### Dada la matriz numpy X, muestra el primer elemento en la primera fila

In [62]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X[0,0]

1

#### Dada la matriz numpy X, muestra el último elemento en la última fila

In [65]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X[2,2]

9

#### Dada la matriz numpy X, muestra los elementos de la fila central

In [71]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
X[1:-1, 1:-1]

array([[5]])

#### Dada la matriz numpy X, muestre los dos primeros elementos en las dos primeras filas

In [88]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[:2, :2]

array([[1, 2],
       [5, 6]])

#### Dada la matriz numpy X, muestre los dos últimos elementos en las dos últimas filas

In [91]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

## Manipulación de matriz

### Convierta la matriz numpy de enteros dada en flotante

In [108]:
X = [-5, -3, 0, 10, 40]
X = np.array(X, dtype = float)
print(X, X.dtype)

[-5. -3.  0. 10. 40.] float64


#### Invierta la matriz numérica dada (el primer elemento se convierte en el último)

In [129]:
X = [-5, -3, 0, 10, 40]
X[::-1]

[40, 10, 0, -3, -5]

#### Ordenar (clasificar) la matriz numpy dada

In [148]:
X = [0,1,-2,-1,12,53,-10]
np.sort(X, axis = None)

array([-10,  -2,  -1,   0,   1,  12,  53])

#### Dada la matriz numpy X, establezca el quinto elemento igual a 1

In [167]:
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Dada la matriz numpy X, cambie el 50 con un 40

In [169]:
X = np.array([10,30,20,60,50])
X[-1] = 40
X

array([10, 30, 20, 60, 40])

#### Dada la matriz numpy X, cambie la última fila con todos los 1

In [178]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array((1,1,1,1))
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

#### Dada la matriz numérica X, cambie el último elemento en la última fila con un 0

In [179]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

#### Dada la matriz numpy X, agregue 5 a cada elemento

In [188]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## Arreglos booleanos (también llamados máscaras)

#### Dada la matriz numpy X, haga una máscara que muestre elementos negativos

In [191]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

#### Dada la matriz numpy X, obtenga los elementos negativos

In [194]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

#### Dada la matriz numpy X, obtenga números superiores a 5

In [195]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X >= 5
X[mask]

array([ 5,  6, 10])

#### Dada la matriz numpy X, obtenga números más altos que la media de los elementos

In [199]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > np.mean(X)
X[mask]

array([ 2,  5,  6, 10])

#### Dada la matriz numpy X, obtenga números iguales a 2 o 10

In [205]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = (X == 2) | (X == 10) 
X[mask]

array([ 2, 10])

## Funciones lógicas

#### Dada la matriz numpy X, devuelve True si ninguno de sus elementos es cero

In [208]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

False

#### Dada la matriz numpy X, devuelve True si alguno de sus elementos es cero

In [209]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

True

## Resumen estadístico

#### Dada la matriz numpy X, muestra la suma de sus elementos

In [211]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

X.sum()

43

#### Dada la matriz numpy X, muestra el valor medio de sus elementos

In [223]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

X.mean()

4.777777777777778

#### Dada la matriz numpy X, mostrar la suma de sus columnas

In [227]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


X.sum(axis = 0) # Recorda: eje=0 columnas; eje=1 filas

array([28, 32, 36, 40])

#### Dada la matriz numpy X, muestra el valor medio de sus filas

In [228]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

#### Dada la matriz numpy X, muestra el valor máximo de sus elementos

In [229]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.max()

16