In [1]:
import sys
import numpy as np

## Matriz numpy basica

In [15]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [17]:
a = np.array([1,2,3,4])

In [20]:
b = np.array([0, .5, 1, 1.5, 2])

In [19]:
a[0], a[1]

(1, 2)

In [21]:
a[0:]

array([1, 2, 3, 4])

In [24]:
a[1:3]

array([2, 3])

In [25]:
a[1:-1]

array([2, 3])

In [26]:
a[::2]

array([1, 3])

In [27]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [28]:
b[[0,2, -1]]

array([0., 1., 2.])

## Tipo de matrices

In [29]:
a

array([1, 2, 3, 4])

In [30]:
a.dtype

dtype('int64')

In [31]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [32]:
b.dtype

dtype('float64')

In [33]:
np.array([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [34]:
c = np.array(['a','b','c'])

In [35]:
c.dtype

dtype('<U1')

In [36]:
d = np.array([{'1':1}, sys])

In [37]:
d.dtype

dtype('O')

## Dimensiones y formas

In [46]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [40]:
A.shape

(2, 3)

In [42]:
A.ndim

2

In [47]:
A.size

6

In [48]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [49]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [50]:
B.shape

(2, 2, 3)

In [51]:
B.ndim

3

In [52]:
B.size

12

## Si la forma no es consistente, simplemente volverá a los objetos regulares de Python

In [55]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/tmp/ipykernel_6597/548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [56]:
C.dtype

dtype('O')

In [57]:
C.shape

(2,)

In [58]:
C.size

2

In [ ]:
type(C[0])

## Indexación y corte de matrices

In [60]:
# Matriz cuadrada

A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [63]:
A[1]

array([4, 5, 6])

In [64]:
A[1][0]

4

In [65]:
# A [d1,d2,d3,d4]

A[1,0]

4

In [69]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [71]:
A[:2, 2:]

array([[3],
       [6]])

In [72]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
A[1] = np.array([10, 10, 10])

In [74]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [75]:
A[2] = 99

In [76]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Resumen estadístico

In [77]:
a = np.array([1, 2, 3, 4])

In [26]:
# Suma de elementos de matriz sobre un eje dado

a.sum()

10

In [79]:
# Calcule la media aritmética a lo largo del eje especificado

a.mean()

2.5

In [80]:
# Calcule la desviación estándar a lo largo del eje especificado

a.std()

1.118033988749895

In [81]:
# Calcule la varianza a lo largo del eje especificado

a.var()

1.25

In [83]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [84]:
A.sum()

45

In [85]:
A.mean()

5.0

In [86]:
A.std()

2.581988897471611

In [89]:
A.sum(axis=0)

array([12, 15, 18])

In [90]:
A.sum(axis=1)

array([ 6, 15, 24])

In [91]:
A.mean(axis=0)

array([4., 5., 6.])

In [92]:
A.mean(axis=1)

array([2., 5., 8.])

In [93]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [94]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Operaciones de radiodifusión y vectorizadas

In [3]:
a = np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a + 10

array([10, 11, 12, 13])

In [6]:
a * 10

array([ 0, 10, 20, 30])

In [7]:
a

array([0, 1, 2, 3])

In [8]:
a += 100

In [9]:
a

array([100, 101, 102, 103])

In [2]:
l = [0,1,2,3]

In [11]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [14]:
a = np.arange(4)

In [15]:
a

array([0, 1, 2, 3])

In [16]:
b = np.array([10,10,10,10])

In [17]:
b

array([10, 10, 10, 10])

In [18]:
a + b

array([10, 11, 12, 13])

In [19]:
a * b

array([ 0, 10, 20, 30])

## Arreglos booleanos

In [27]:
a = np.arange(4)

In [28]:
a

array([0, 1, 2, 3])

In [33]:
a[0], a[-1]

(0, 3)

In [34]:
a[[0, -1]]

array([0, 3])

In [37]:
a[[True, False, False,True]]

array([0, 3])

In [38]:
a

array([0, 1, 2, 3])

In [40]:
a >= 2

array([False, False,  True,  True])

In [41]:
a[a >= 2]

array([2, 3])

In [42]:
a.mean()

1.5

In [43]:
a[a > a.mean()]

array([2, 3])

In [44]:
a[~(a > a.mean())]

array([0, 1])

In [49]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [51]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [52]:
A = np.random.randint(100, size=(3, 3))

In [53]:
A

array([[68, 34, 66],
       [69,  6, 65],
       [84,  7, 92]])

In [54]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([68, 66,  6, 84, 92])

In [55]:
A > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [56]:
A[Am> 30]

array([68, 34, 66, 69, 65, 84, 92])

## Algrebra lineal

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [58]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [59]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [60]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [61]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [62]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Tamaño de los objetos en la memoria

### ints, floats

In [3]:
# Un entero en Python es > 24 bytes

sys.getsizeof(1)

28

In [4]:
# Los largos son aún más grandes

sys.getsizeof(10**100)

72

In [5]:
# El tamaño de Numpy es mucho más pequeño

np.dtype(int).itemsize

8

In [6]:
# El tamaño de Numpy es mucho más pequeño

np.dtype(np.int8).itemsize

1

In [7]:
np.dtype(float).itemsize

8

## Las listas son aún más grandes

In [8]:
# Una lista de un elemento

sys.getsizeof([1])

64

In [10]:
# Una matriz de un elemento en numpy

np.array([1]).nbytes

8

## Y el rendimiento también es importante

In [11]:
l = list(range(100000))

In [12]:
a = np.arange(100000)

In [13]:
%time np.sum(a ** 2)

CPU times: user 0 ns, sys: 1.95 ms, total: 1.95 ms
Wall time: 2.65 ms


333328333350000

In [14]:
%time sum([x ** 2 for x in l])

CPU times: user 19.5 ms, sys: 0 ns, total: 19.5 ms
Wall time: 19 ms


333328333350000

## Funciones útiles de Numpy

### Random

In [17]:
np.random.random(size=2)

array([0.0016807 , 0.99681901])

In [18]:
np.random.normal(size=2)

array([-0.82780315,  0.834373  ])

In [19]:
np.random.rand(2, 4)

array([[0.53914535, 0.55761724, 0.90758113, 0.64443671],
       [0.3637827 , 0.10027019, 0.84122074, 0.60191588]])

### Arange

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [22]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### Reshape

In [23]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Lindspace

In [28]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [30]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((3, 3), dtype=np.int)

/tmp/ipykernel_6634/383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### identity and eye

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [63]:
"Hello World"[6]

'W'