# Cargamos numpy (recuerde install pip numpy primero)

In [2]:
import numpy as np

# Lo basico

In [ ]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

In [21]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Devuelve el número de dimensiones del array
a.ndim

In [22]:
# Devuelve una tupla con las dimensiones del array (fila, columna)
b.shape

(2, 3)

In [ ]:
# Devuelve el tipo de datos de los elementos del array 
a.dtype

In [ ]:
# Obtener longitud de un elemento de matriz en bytes
a.itemsize

In [ ]:
# Obtener el tamaño total
a.nbytes

# acceder/cambiar elementos específicos, filas, columnas, etc.

In [18]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Obtener un elemento [r,c]
a[1, -2]
print(a)

In [ ]:
# Obtener una fila específica
a[0, :]
a

In [ ]:
# Obtener una columna específica
a[:, -1]
a

In [ ]:
#Poniéndose un poco más elegante [startindex, endindex, step size]
a[0, 1:-1:2]
a

In [ ]:
a[:,2] = [1,2]
print(a)

* 3-d ejemplo

In [ ]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

In [ ]:
# Obtener un elemento específico (trabajar afuera adentro)
b[:,0,0]

In [ ]:
# Remplazar
b[:,1,:] = [[9,9],[8,8]]

In [ ]:
b

# Inicializar diferentes arreglos

In [8]:
# Todos 0 matriz
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# Todos 1 matriz
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [16]:
# Cualquier otro numero
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [19]:
# Cualquier otro numero (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
# Números decimales aleatorios
np.random.rand(4,2)

array([[0.88931959, 0.32679137],
       [0.26972876, 0.19980947],
       [0.88451734, 0.55367887],
       [0.99472109, 0.52252143]])

In [65]:
# Números enteros aleatorios
np.random.randint(8, size=(3,3))

array([[4, 0, 5],
       [0, 2, 3],
       [0, 1, 0]])

In [70]:
# La matriz de identidad es una matriz cuadrada con unos en la diagonal principal
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
# Repetir una matriz
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1, 1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
output = np.zeros((7,7))

z = np.ones((5, 5))
z[2, 2] = 5

output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# Matematicas

In [108]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [109]:
a + 2

array([3, 4, 5, 6])

In [110]:
a - 2

array([-1,  0,  1,  2])

In [111]:
a * 2

array([2, 4, 6, 8])

In [112]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [113]:
a ** 2

array([ 1,  4,  9, 16])

In [114]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [115]:
# Seno trigonométrico, por elementos
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Algebra lineal

In [126]:
a = np.ones((2,3))
print(a)

b = np.full((3, 2),2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [130]:
# Encontrar el determinante

c = np.identity(3)
np.linalg.det(c)

1.0

# Estadisticas

In [57]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
np.min(stats)

1

In [59]:
np.max(stats, axis =1)

array([3, 6])

In [61]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# Reorganizacion de arreglos

In [35]:
antes = np.array([[1,2,3,4,],[5,6,7,8,]])
print(antes)

despues = antes.reshape(4,2)
print(despues)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [39]:
# Apilamiento vertical

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1, v2, v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
# Pila horizontal

h1 = np.ones((2,4))
h2 = np.zeros((2,2,))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# misceláneas
## cargar datos del archivo

In [50]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([[ 1,  2,  3, 52, 45, 75, 42, 15, 50,  2,  6, 67],
       [32, 52, 67, 87, 43, 12, 87, 53, 67, 97, 11, 12]], dtype=int32)

### Enmascaramiento booleano e indexación avanzada

In [69]:
((filedata > 50) & (filedata < 100))

array([[False, False, False,  True, False,  True, False, False, False,
        False, False,  True],
       [False,  True,  True,  True, False, False,  True,  True,  True,
         True, False, False]])

In [55]:
## Puedes indexar con una lista en numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [100]:
a = np.random.randint(10, size =(6,5))
print(a)
a[2:4, 0:2]
a[[0,1,2,3],[1,2,3,4]]
a[[0,4,5],3:]

[[3 8 2 4 6]
 [0 7 8 3 3]
 [5 4 6 6 6]
 [6 4 6 1 3]
 [4 9 8 6 0]
 [7 1 3 0 3]]


array([[4, 6],
       [6, 0],
       [0, 3]])